### ISSUE TITLE
Configuración de scripts para integración continua con el entorno de staging

### ISSUE THREAD

**Issue by oxcar** [CodeandoMexico/decidim-monterrey#18]
Automatizar como se hace deploy de la app al entorno de staging.

- Una posibilidad es hacerlo con GitHub Actions

**Comment by basicavisual** [comment]
también evaluar capistrano. Revisar esta página https://github.com/Platoniq/decidim-install/blob/main/advanced-deploy.md

**Comment by oxcar** [comment]
Este issue ya no es necesario. En staging se clona el repo y se levanta el proyecto con Docker compose + variables de entorno.
