### ISSUE TITLE
La carpeta para subir ficheros en el entorno de staging debe ser un volumen independiente

### ISSUE THREAD

**Issue by oxcar** [CodeandoMexico/decidim-monterrey#19]
En el entorno de staging, la carpeta para subir ficheros debe estar en una carpeta independiente para que no se borre cuando hagamos subidas de nuevas versiones.

**Comment by basicavisual** [comment]
en capistrano se puede configurar los directorios que se ignoran en el deploy. Los archivos que se suben, se suben a la carpeta `storage`

**Comment by oxcar** [comment]
En staging y en producción se va a manejar como una carpeta externa a Decidim, de manera que cuando se reinstale no se pierdan la carpeta con las subidas.

Esto se configura con Docker compose.
