### ISSUE TITLE
Configuración de Cron Jobs en el entorno de Staging

### ISSUE THREAD

**Issue by oxcar** [CodeandoMexico/decidim-monterrey#20]
Referencia (schedulled tasks)
https://docs.decidim.org/en/install/#scheduled_tasks

**Comment by basicavisual** [comment]
También evaluar esta opción `delayed_job_active_record` https://github.com/Platoniq/decidim-install/blob/main/basic-config.md

Los cron jobs se ocupan de repartir tareas tales como el envío de correos

**Comment by basicavisual** [comment]
relacionada a la tarea #22
