### ISSUE TITLE
Configuración básica de look & feel

### ISSUE THREAD

**Issue by oxcar** [CodeandoMexico/decidim-monterrey#6]
Cambiar colores básicos y logitpos.

Referencias:
https://docs.decidim.org/en/admin/appearance/

**Comment by oxcar** [comment]
![apariencia](https://user-images.githubusercontent.com/2067516/151435405-6af217ab-c035-4b02-8c0f-490c5dca02a3.png)

**Comment by basicavisual** [comment]
se realizará en con el municipio de monterrey
